package docs

import (
	"bytes"
	"strings"
	"testing"

	"github.com/ThousifXahamed079/gatekeeper/internal/schema"
)

func TestGenerateEnvExample(t *testing.T) {
	tests := []struct {
		name     string
		schema   *schema.Schema
		contains []string
		excludes []string
	}{
		{
			name: "basic header",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "API_KEY", Type: "string", Required: true},
				},
			},
			contains: []string{
				"# Environment Variables",
				"# Generated by Gatekeeper",
				"API_KEY=",
			},
		},
		{
			name: "required var is uncommented",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "REQUIRED_VAR", Type: "string", Required: true},
				},
			},
			contains: []string{
				"REQUIRED_VAR=",
			},
		},
		{
			name: "optional var without default is commented",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "OPTIONAL_VAR", Type: "string", Required: false},
				},
			},
			contains: []string{
				"# OPTIONAL_VAR=",
			},
		},
		{
			name: "optional var with default is uncommented",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "OPT_WITH_DEFAULT", Type: "string", Required: false, Default: "default_val"},
				},
			},
			contains: []string{
				"OPT_WITH_DEFAULT=default_val",
			},
		},
		{
			name: "example value takes priority",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "VAR", Type: "string", Example: "example_value", Default: "default_value"},
				},
			},
			contains: []string{
				"VAR=example_value",
			},
			excludes: []string{
				"VAR=default_value",
			},
		},
		{
			name: "default value when no example",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "VAR", Type: "string", Default: "default_value"},
				},
			},
			contains: []string{
				"VAR=default_value",
			},
		},
		{
			name: "enum uses first allowed value",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "LOG_LEVEL", Type: "enum", Required: true, AllowedValues: []string{"debug", "info", "warn"}},
				},
			},
			contains: []string{
				"LOG_LEVEL=debug",
			},
		},
		{
			name: "type placeholder for string",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "VAR", Type: "string", Required: true},
				},
			},
			contains: []string{
				"VAR=your_value_here",
			},
		},
		{
			name: "type placeholder for url",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "URL", Type: "url", Required: true},
				},
			},
			contains: []string{
				"URL=https://example.com",
			},
		},
		{
			name: "description comment",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "VAR", Type: "string", Required: true, Description: "This is a description"},
				},
			},
			contains: []string{
				"# This is a description",
			},
		},
		{
			name: "sensitive indicator",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "SECRET", Type: "string", Required: true, Sensitive: true},
				},
			},
			contains: []string{
				"Sensitive",
			},
		},
		{
			name: "group headers",
			schema: &schema.Schema{
				Version: "1",
				Groups: []schema.Group{
					{Name: "Database", Description: "Database settings"},
				},
				Vars: []schema.Var{
					{Name: "DB_HOST", Type: "string", Required: true, Group: "Database"},
				},
			},
			contains: []string{
				"# Database",
				"# Database settings",
			},
		},
		{
			name: "ungrouped header when groups exist",
			schema: &schema.Schema{
				Version: "1",
				Groups: []schema.Group{
					{Name: "Database", Description: "Database settings"},
				},
				Vars: []schema.Var{
					{Name: "DB_HOST", Type: "string", Required: true, Group: "Database"},
					{Name: "RANDOM", Type: "string", Required: true},
				},
			},
			contains: []string{
				"# Database",
				"# Ungrouped",
			},
		},
		{
			name: "value with spaces is quoted",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "MSG", Type: "string", Required: true, Default: "hello world"},
				},
			},
			contains: []string{
				`MSG="hello world"`,
			},
		},
		{
			name: "type info in constraints",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "PORT", Type: "port", Required: true},
				},
			},
			contains: []string{
				"Type: port",
				"Required",
			},
		},
		{
			name: "enum type shows values in constraints",
			schema: &schema.Schema{
				Version: "1",
				Vars: []schema.Var{
					{Name: "ENV", Type: "enum", Required: true, AllowedValues: []string{"dev", "prod"}},
				},
			},
			contains: []string{
				"Type: enum(dev, prod)",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var buf bytes.Buffer
			err := GenerateEnvExample(tt.schema, &buf)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			output := buf.String()

			for _, expected := range tt.contains {
				if !strings.Contains(output, expected) {
					t.Errorf("expected output to contain %q, got:\n%s", expected, output)
				}
			}

			for _, excluded := range tt.excludes {
				if strings.Contains(output, excluded) {
					t.Errorf("expected output to NOT contain %q, got:\n%s", excluded, output)
				}
			}
		})
	}
}

func TestGetTypePlaceholder(t *testing.T) {
	tests := []struct {
		varType  string
		expected string
	}{
		{schema.TypeString, "your_value_here"},
		{schema.TypeInteger, "0"},
		{schema.TypeFloat, "0.0"},
		{schema.TypeBoolean, "true"},
		{schema.TypeURL, "https://example.com"},
		{schema.TypeEmail, "user@example.com"},
		{schema.TypePort, "8080"},
		{schema.TypeFilepath, "/path/to/file"},
		{schema.TypeDuration, "30s"},
		{"unknown", "value"},
	}

	for _, tt := range tests {
		t.Run(tt.varType, func(t *testing.T) {
			result := getTypePlaceholder(tt.varType)
			if result != tt.expected {
				t.Errorf("expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestMaybeQuote(t *testing.T) {
	tests := []struct {
		name     string
		value    string
		expected string
	}{
		{name: "simple value", value: "hello", expected: "hello"},
		{name: "value with space", value: "hello world", expected: `"hello world"`},
		{name: "value with tab", value: "hello\tworld", expected: "\"hello\tworld\""},
		{name: "value with hash", value: "hello#world", expected: `"hello#world"`},
		{name: "value with equals", value: "a=b", expected: `"a=b"`},
		{name: "value with quotes", value: `say "hello"`, expected: `"say \"hello\""`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := maybeQuote(tt.value)
			if result != tt.expected {
				t.Errorf("expected %q, got %q", tt.expected, result)
			}
		})
	}
}

func TestGetExampleValue(t *testing.T) {
	tests := []struct {
		name     string
		v        schema.Var
		expected string
	}{
		{
			name:     "example takes priority",
			v:        schema.Var{Type: "string", Example: "example", Default: "default"},
			expected: "example",
		},
		{
			name:     "default when no example",
			v:        schema.Var{Type: "string", Default: "default"},
			expected: "default",
		},
		{
			name:     "allowed value when no example or default",
			v:        schema.Var{Type: "enum", AllowedValues: []string{"first", "second"}},
			expected: "first",
		},
		{
			name:     "type placeholder when nothing else",
			v:        schema.Var{Type: "string"},
			expected: "your_value_here",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := getExampleValue(tt.v)
			if result != tt.expected {
				t.Errorf("expected %q, got %q", tt.expected, result)
			}
		})
	}
}
