package docs

import (
	"fmt"
	"io"
	"strings"

	"github.com/ThousifXahamed079/gatekeeper/internal/schema"
)

// GenerateEnvExample generates an example .env file from a schema.
func GenerateEnvExample(s *schema.Schema, w io.Writer) error {
	// Header comment
	fmt.Fprintln(w, "# Environment Variables")
	fmt.Fprintln(w, "#")
	fmt.Fprintln(w, "# Generated by Gatekeeper — do not edit manually.")
	fmt.Fprintln(w, "# Regenerate: gatekeeper docs --format env-example --out .env.example")
	fmt.Fprintln(w)

	groups := organizeByGroup(s)

	for i, gv := range groups {
		// Add blank line between groups (but not before the first)
		if i > 0 {
			fmt.Fprintln(w)
		}

		// Group header comment
		if gv.Group != nil {
			fmt.Fprintf(w, "# %s\n", strings.Repeat("=", 60))
			fmt.Fprintf(w, "# %s\n", gv.Group.Name)
			if gv.Group.Description != "" {
				fmt.Fprintf(w, "# %s\n", gv.Group.Description)
			}
			fmt.Fprintf(w, "# %s\n", strings.Repeat("=", 60))
		} else if len(s.Groups) > 0 {
			// Only show "Ungrouped" header if there are other groups
			fmt.Fprintf(w, "# %s\n", strings.Repeat("=", 60))
			fmt.Fprintln(w, "# Ungrouped")
			fmt.Fprintf(w, "# %s\n", strings.Repeat("=", 60))
		}

		// Render each variable
		for _, v := range gv.Vars {
			renderEnvVar(v, w)
		}
	}

	return nil
}

// renderEnvVar renders a single variable in .env example format.
func renderEnvVar(v schema.Var, w io.Writer) {
	// Description comment
	if v.Description != "" {
		fmt.Fprintf(w, "# %s\n", v.Description)
	}

	// Type and constraint info
	var constraints []string

	// Type
	if v.Type == schema.TypeEnum && len(v.AllowedValues) > 0 {
		constraints = append(constraints, fmt.Sprintf("Type: enum(%s)", strings.Join(v.AllowedValues, ", ")))
	} else {
		constraints = append(constraints, fmt.Sprintf("Type: %s", v.Type))
	}

	// Required
	if v.Required {
		constraints = append(constraints, "Required")
	} else {
		constraints = append(constraints, "Optional")
	}

	// Sensitive
	if v.Sensitive {
		constraints = append(constraints, "Sensitive")
	}

	fmt.Fprintf(w, "# [%s]\n", strings.Join(constraints, " | "))

	// The variable line
	value := getExampleValue(v)

	// Comment out if not required and no default
	if !v.Required && v.Default == "" {
		fmt.Fprintf(w, "# %s=%s\n", v.Name, value)
	} else {
		fmt.Fprintf(w, "%s=%s\n", v.Name, value)
	}
}

// getExampleValue determines the best example value for a variable.
func getExampleValue(v schema.Var) string {
	// Priority: Example > Default > AllowedValues[0] > type-based placeholder
	if v.Example != "" {
		return maybeQuote(v.Example)
	}

	if v.Default != "" {
		return maybeQuote(v.Default)
	}

	if len(v.AllowedValues) > 0 {
		return v.AllowedValues[0]
	}

	return getTypePlaceholder(v.Type)
}

// getTypePlaceholder returns a placeholder value based on the variable type.
func getTypePlaceholder(t string) string {
	switch t {
	case schema.TypeString:
		return "your_value_here"
	case schema.TypeInteger:
		return "0"
	case schema.TypeFloat:
		return "0.0"
	case schema.TypeBoolean:
		return "true"
	case schema.TypeURL:
		return "https://example.com"
	case schema.TypeEmail:
		return "user@example.com"
	case schema.TypePort:
		return "8080"
	case schema.TypeFilepath:
		return "/path/to/file"
	case schema.TypeDuration:
		return "30s"
	default:
		return "value"
	}
}

// maybeQuote wraps a value in quotes if it contains spaces or special characters.
func maybeQuote(value string) string {
	if strings.ContainsAny(value, " \t\n\r#=") {
		// Use double quotes and escape any existing quotes
		escaped := strings.ReplaceAll(value, "\"", "\\\"")
		return fmt.Sprintf("\"%s\"", escaped)
	}
	return value
}
