package docs

import (
	"fmt"
	"io"
	"strings"

	"github.com/ThousifXahamed079/gatekeeper/internal/schema"
)

// GroupedVars holds variables organized by their group.
type GroupedVars struct {
	Group *schema.Group // nil for ungrouped vars
	Vars  []schema.Var
}

// organizeByGroup organizes schema variables by their declared group.
// It returns groups in schema order with ungrouped vars at the end.
func organizeByGroup(s *schema.Schema) []GroupedVars {
	// If no groups defined, return all vars as a single flat list (no grouping)
	if len(s.Groups) == 0 {
		return []GroupedVars{{Group: nil, Vars: s.Vars}}
	}

	// Map of group name → []Var
	groupVars := make(map[string][]schema.Var)
	var ungrouped []schema.Var

	// Distribute vars to their groups
	for _, v := range s.Vars {
		if v.Group == "" {
			ungrouped = append(ungrouped, v)
		} else {
			groupVars[v.Group] = append(groupVars[v.Group], v)
		}
	}

	// Build result in schema.Groups order
	result := make([]GroupedVars, 0, len(s.Groups)+1)
	for i := range s.Groups {
		g := &s.Groups[i]
		result = append(result, GroupedVars{
			Group: g,
			Vars:  groupVars[g.Name],
		})
	}

	// Append ungrouped vars at the end (if any)
	if len(ungrouped) > 0 {
		result = append(result, GroupedVars{
			Group: nil,
			Vars:  ungrouped,
		})
	}

	return result
}

// GenerateMarkdown generates markdown documentation from a schema.
func GenerateMarkdown(s *schema.Schema, w io.Writer) error {
	// Header
	fmt.Fprintln(w, "# Environment Variables")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "> Generated by [Gatekeeper](https://github.com/ThousifXahamed079/gatekeeper)")
	fmt.Fprintln(w, "> — do not edit manually.")
	fmt.Fprintln(w, ">")
	fmt.Fprintln(w, "> Regenerate: `gatekeeper docs --out ENV.md`")
	fmt.Fprintln(w)

	groups := organizeByGroup(s)

	for _, gv := range groups {
		// Render group heading
		if gv.Group != nil {
			fmt.Fprintf(w, "## %s\n", gv.Group.Name)
			if gv.Group.Description != "" {
				fmt.Fprintln(w, gv.Group.Description)
			}
			fmt.Fprintln(w)
		} else if len(s.Groups) > 0 {
			// Only show "Ungrouped" heading if there are other groups
			fmt.Fprintln(w, "### Ungrouped")
			fmt.Fprintln(w)
		}

		// Render table or empty message
		if len(gv.Vars) == 0 {
			fmt.Fprintln(w, "*No variables in this group.*")
			fmt.Fprintln(w)
		} else {
			if err := renderTable(gv.Vars, w); err != nil {
				return err
			}
			fmt.Fprintln(w)
		}
	}

	return nil
}

// renderTable renders a markdown table for the given variables.
func renderTable(vars []schema.Var, w io.Writer) error {
	// Table header
	fmt.Fprintln(w, "| Name | Type | Required | Default | Description |")
	fmt.Fprintln(w, "|------|------|----------|---------|-------------|")

	for _, v := range vars {
		name := formatName(v)
		varType := formatType(v)
		required := formatRequired(v)
		defaultVal := formatDefault(v)
		description := formatDescription(v)

		fmt.Fprintf(w, "| %s | %s | %s | %s | %s |\n",
			name, varType, required, defaultVal, description)
	}

	return nil
}

// formatName formats the variable name with optional sensitive indicator.
func formatName(v schema.Var) string {
	if v.Sensitive {
		return fmt.Sprintf("`%s` 🔒", v.Name)
	}
	return fmt.Sprintf("`%s`", v.Name)
}

// formatType formats the type with enum values if applicable.
func formatType(v schema.Var) string {
	if v.Type == schema.TypeEnum && len(v.AllowedValues) > 0 {
		return formatEnumType(v.AllowedValues)
	}
	return fmt.Sprintf("`%s`", v.Type)
}

// formatEnumType formats an enum type with values.
// Shows first 3 values + ellipsis if more than 5 values.
func formatEnumType(values []string) string {
	if len(values) > 5 {
		return fmt.Sprintf("`enum(%s, ...)`", strings.Join(values[:3], ", "))
	}
	return fmt.Sprintf("`enum(%s)`", strings.Join(values, ", "))
}

// formatRequired formats the required column.
func formatRequired(v schema.Var) string {
	if v.Required {
		return "✅ Yes"
	}
	return "No"
}

// formatDefault formats the default value column.
func formatDefault(v schema.Var) string {
	if v.Default == "" {
		return "—"
	}
	return fmt.Sprintf("`%s`", v.Default)
}

// formatDescription formats the description column.
func formatDescription(v schema.Var) string {
	if v.Description == "" {
		return "—"
	}
	// Escape pipe characters to avoid breaking the table
	return strings.ReplaceAll(v.Description, "|", "\\|")
}
